zeromq/azmq

config/FindZeroMQ.cmake
Fixes issue #57 CMake somehow fails to find libzmq on Windows 8.1 x64 with
VS2013
=> Search for official ZMQ library names on Windows

azmq/message.hpp
This implicit cast from azmq::message to boost::asio::const_buffer makes azmq::message_vector satisfy ConstBufferSequence, so it can be used directly in a send() call to send a multipart message.
=> make message_vector satisfy ConstBufferSequence for direct use in send()

azmq/detail/socket_service.hpp
Fix for issue *100% CPU load in idle mode when router_socket (ZMQ_ROUTER) is used*.
The fix adds a checking of `ZMQ_POLLIN` and `ZMQ_POLLOUT` events after each send and receive operations to compliment waiting for events on `ZMQ_FD`.
=> 100% CPU load in idle mode when router_socket (ZMQ_ROUTER) is used (#81)

config/FindZeroMQ.cmake
On Windows it's not possible to use release version of ZeroMQ with debug
version of AZMQ-based application because global CRT variable `errno` is
not shared between debug CRT library and release CRT library.
Check http://www.drdobbs.com/avoiding-the-visual-c-runtime-library/184416623
=> On Windows debug version of AZMQ uses debug ZeroMQ

azmq/message.hpp
For performance reasons I need to construct an azmq::message with a buffer that doesn't get copied. These constructors use zmq_msg_init_data() with the optional free function.
=> zero-copy message constructors

azmq/message.hpp
Zero-copy versions of message constructors that take asio buffers.
Removed the raw buffer constructors.
=> zero-copy asio buffer constructors

azmq/detail/socket_ops.hpp, azmq/detail/socket_service.hpp, azmq/socket.hpp
Code was mostly there already, this now closes the underlying descriptor
as well which will terminate the currently waiting operation and remove
the socket from the poll.
=> Resolve #100 implement close method

CMakeLists.txt
When azmq is build as a child project using `add_directory` command in parent `CMakeLists.txt` then child `CMakeLists.txt` in `azmq` folder sets `CMAKE_MODULE_PATH` relative to the folder where parent `CMakeLists.txt` resides. As a result discovery of ZeroMQ libraries fails.
Using `CMAKE_CURRENT_SOURCE_DIR` to set `CMAKE_MODULE_PATH` removes that problem.
=> Set CMAKE_MODULE_PATH relative to CMAKE_CURRENT_SOURCE_DIR

test/signal/CMakeLists.txt, test/socket_ops/CMakeLists.txt
When building azmq under buildroot, signal and socket_ops tests run into
a similar linker error as the socket test did in issue #118. Simply
adding CMAKE_THREAD_LIBS_INIT to the linked libraries for those tests
resolves the issue.
Resolves issue #130
=> Add missing CMAKE_THREAD_LIBS_INIT to tests

azmq/detail/socket_ops.hpp, azmq/detail/socket_service.hpp
Asio guarantees asynchronous operations will never see an error_code of errc::interrupted, azmq should mirror this behavior
=> Fix issue with errc::interrupted being periodically returned to Async operations

azmq/detail/basic_io_object.hpp, azmq/socket.hpp
Trivial change; tested on Arch Linux ARM, GCC 7.2.1, Boost 1.66
=> Replaced boost::basic_io_object::implementation with get_implemetation()

CMakeLists.txt, README.md, azmq/detail/context_ops.hpp, azmq/detail/socket_ops.hpp, azmq/detail/socket_service.hpp, azmq/error.hpp, azmq/message.hpp
Modifying mutex reference
Conditional define for BOOST_SYSTEM_NOEXCEPT
Conditional drop of string_ref reference
Option to disable tests which aren't adopted for older boost
Removed Boost log component reference in find_package
Decreased Boost version requirement in find_package.
=> Pull request for #138 Boost 1.48 compatibility

azmq/detail/send_op.hpp, test/socket/main.cpp
The `send_buffer_op_base` object only saved a reference to the `boost::asio::const_buffer` object given to `async_send()`. This required callers to ensure the same life-time for the boost::asio::const_buffer as for the underlying memory it refers to, which seems like an unnecessarily strict requirement.
Normally with boost::asio, the caller only has to ensure the proper life-time of the underlying memory, not the buffer object itself. `receive_buffer_op_base` already saves a copy, so it seems better for `send_buffer_op_base` to do the same.
This fixes #145.
=> Fix dangling reference to buffer object for async_send() operations

azmq/detail/socket_ops.hpp
boost.format is rather bloated. we can easily replace this with simple
string arithmetics here
=> azmq: avoid boost.format

azmq/detail/actor_service.hpp, azmq/detail/socket_service.hpp
This fixes #153 
Macro BOOST_VERSION consists of 6 digits (https://www.boost.org/doc/libs/1_70_0/boost/version.hpp)
=> Fixed comparison for BOOST_VERSION

azmq/socket.hpp
The alias for socket option ZMQ_ROUTER_HANDOVER was missing
=> add another type alias for socket option

CMakeLists.txt, azmq/detail/socket_ops.hpp
we can reduce the dependencies onto a boost.regex library by using
std::regex and friends.
furthermore we can cache the compiled regex instead of building it
every time
=> azmq: replace boost.regex with std

AUTHORS, azmq/detail/socket_ops.hpp
mt19937 is a great rng, but it requires a rather large state. taus88 is
a very decent rng with a much smaller memory footprint
=> socket ops: use taus88 instead of mersenne_twister

azmq/detail/socket_ops.hpp
`last` is a signed type, while `0u` is an unsigned type, but we
obviously want to have `index` and `last` to be of the same type (well,
we typically don't care too much, but compilers can be quite naggy about
signed/unsigned comparisons)
=> socket_ops: silence signed/unsigned comparison warning

azmq/detail/context_ops.hpp
Without this patch, max_sockets references ZMQ_MAXMSGSIZE which
isn't quite right ;) Probably a typo - lets just quickly fix it!
I've tested this locally by subscribing to >1000 topics to avoid
the proverbial "Too many open files" and already ensuring that
my 'ulimit -n <>' soft & hard limits allow for the extra sockets.
=> azmq/detail/context_ops.hpp: Assign ZMQ_MAX_SOCKETS to max_sockets

azmq/detail/context_ops.hpp, test/context_ops/main.cpp
This looks like a typo
The zmq_ctx_set() function returns zero if successful. Otherwise it returns -1 and sets errno ...
http://api.zeromq.org/4-0:zmq-ctx-set
=> context_ops: fix bug handling zmq_ctx_set result

azmq/detail/reactor_op.hpp, azmq/detail/receive_op.hpp, azmq/detail/send_op.hpp, azmq/detail/socket_service.hpp, test/socket/main.cpp
Previously, ops were tracked in `boost::intrusive::list`s and deleted by unlinking from the list and calling `do_complete`, which did the `delete`. However, any remaining ops in the queues during destruction of `per_descriptor_data` were not freed, because `boost::intrusive::list` destruction only unlinks and does not free the nodes.
This patch refactors the op/queue memory management to fix the leak, and separates the memory management from the `do_complete()` action. Now, ops are tracked with `std::deque` + `std::unique_ptr` everywhere. They no longer delete themselves in `do_complete()`, but instead we rely on automatic destructor calls to free the memory. `do_complete()` calls are still done in the same place as before, but now they only call the completion handlers and leave the …
=> Fix leak of remaining pending operations during io_service destruction

azmq/detail/socket_ops.hpp, azmq/message.hpp, azmq/socket.hpp, test/socket/main.cpp
I hope the commit message explains the problem well enough.
The test-case I added fails without the accompanying change to the library, since the message was left emptied (or "nullified" as the zmq docs put it) after `sc.send(snd_msg)` before.
c.f. http://api.zeromq.org/4-0:zmq-msg-send
> The zmq_msg_t structure passed to zmq_msg_send() is nullified during the call. If you want to send the same message to multiple sockets you have to copy it using (e.g. using zmq_msg_copy()).
=> Fix nullification of message const& in socket::send()

CMakeLists.txt
This makes adding the subdirectory `doc` optional in the same way tests are optional.
With this change I can use CMake's FetchContent_Declare and FetchContent_MakeAvailable without any modifications to avoid building the documentation example.
=> Make building documentation examples optional in the same style as tests

azmq/detail/receive_op.hpp, azmq/detail/send_op.hpp, azmq/socket.hpp, test/socket/main.cpp, test/socket_ops/main.cpp
Added test case and solution for fix #212 . 
Ensure that after the completion handler of the async operation, the same thread is still used.
After the completion handler has been completed dispatch the completion handler through the executor of the handler and using the associated allocator of the handler. The handler is moved since it is pretty safe to say that the `do_complete()` function will be the last function called on the object that uses the handler.
Solution based on https://github.com/chriskohlhoff/asio/blob/master/asio/src/examples/cpp14/operations/callback_wrapper.cpp that implements a custom asio operation to show how this is done. 
The `boost::asio::bind_allocator` was only added in Boost version 1.79 and I am not entirely sure how `bind_allocator` works before Boost …
=> Notify the completion handler through the handler's associated executor
